### ISSUE TITLE
Soporte Python3

### ISSUE THREAD

**Issue by Nekmo** [hawk31/MCMC_tfg#2]
Pues yo creo que es muy malvado por su parte no tener en cuenta a la extensa comunidad de usuarios de Python3. Realmente terrible.

Por favor, considere darle soporte, o muestre al menos arrepentimiento.

**Comment by josejimenezluna** [comment]
El soporte de Python3 es dependiente de las implementaciones de lda y BeautifulSoup. Debería ser compatible sin problemas.
