### ISSUE TITLE
¡Incluir licencia!

### ISSUE THREAD

**Issue by Nekmo** [hawk31/MCMC_tfg#3]
¡Qué terrible desdicha! ¡¿Cómo ha podido usted publicar este código sin licencia?! ¿Acaso es usted consciente de los peligros que ello acarrea? Eso me permitiría, si llegase a desearlo, ¡copiar su código para mi propio beneficio! ¡¡Y decir que es mío!! ¡Y entonces sería como usted!

Por favor, tenga en cuenta el trabajo de los programadores. ¡Ponga una licencia a su código! Todos se lo agradeceremos.

**Comment by josejimenezluna** [comment]
El TFG está bajo licencia Creative Commons 4 cc-by. Aún no he decidido si poner licencia al código.

**Comment by ntrrgc** [comment]
> Eso me permitiría, si llegase a desearlo, ¡copiar su código para mi propio beneficio!

Nada más lejos de la verdad. Desde que se estableció el [Convenio de Berna para la protección de las obras literarias y artísticas](https://es.wikipedia.org/wiki/Convenio_de_Berna_para_la_Protecci%C3%B3n_de_las_Obras_Literarias_y_Art%C3%ADsticas) y [se equiparó el software a éstas en EEUU](https://www.law.cornell.edu/uscode/text/17/101) y en otros países ([incluido España](http://www.boe.es/buscar/act.php?id=BOE-A-1996-8930#ddunica)), todos los programas de ordenador están protegidos por el _copyright_.

Esto significa que salvo con el consentimiento del autor (habitualmente en forma de licencia de software escrita) no tienes ningún derecho alguno sobre sus obras. Algunos ejemplos de derechos que podrías echar de menos son ver el código, ejecutarlo o distribuirlo.

Sí es cierto sin embargo que en el caso de un repositorio en GitHub adquieres el derecho a ver el código y hacer forks, debido a que el autor permite estos usos al aceptar los [términos de servicio de GitHub](https://help.github.com/articles/github-terms-of-service/#f-copyright-and-content-ownership).

**Comment by Nekmo** [comment]
Sí. Pero eso no lo sabía hawk31. ¡Y eso era lo importante!
